name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: make test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run make test
        run: make test

  testcover:
    name: make testcover
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run make testcover
        run: make testcover
